# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload eventhandler Python Package

on:
  release:
    types: [published]
  # eigentlich sollte das release genuegen, tut es aber nicht
  workflow_run:
    workflows: [Create e-Release from v-Tag]
    types:
      - completed

permissions:
  contents: read

env:
  DEBUG: 1

jobs:
  deploy:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./eventhandler

    steps:
    - uses: actions/checkout@v3
    - name: abort if not ve*
      if: ${{ !startsWith(github.event.release.tag_name, 'e') }}
      # if: startsWith geht, bei Negation muss aber die {{{}{}{{{-Schlonzweise genutzt werden
      # if: ! startsWith(github.event.release.tag_name, 'e')
      run: |
        echo "aborting, this is not an eventhandler release"
        exit 0
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install wheel
        pip install coshsh
        pip install jinja2
    - name: Build package
      run: |
        python -m build
        pwd
        find .
    - name: README einshoch, weil gh-action-pypi-publish anscheinend working-directory ignoriert
      run: |
        cp README.md ..
    - name: Publish package
      # das hier gibts:
      # /home/runner/work/noteventificationforhandlerwarder/noteventificationforhandlerwarder/eventhandler
      # /home/runner/work/<reponame>/<was beim git clone entsteht>
      # 1 globales working-directory: ./eventhandler
      #   packages-dir: ./eventhandler
      #   sucht nach ls -A './eventhandler/*.whl'
      #   knallt mit IsADirectoryError: [Errno 21] Is a directory: '/github/workspace/eventhandler/dist'
      # 2 versuch mit packages-dir: ./eventhandler/dist
      uses: pypa/gh-action-pypi-publish@v1.8.10
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN_NF }}
        verbose: true
        packages-dir: ./eventhandler/dist
        verify-metadata: false
