on:
  push:
    tags:
      - 'vn*' # trigger this when a tag starting with v is pushed

name: Create n-Release from v-Tag

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: De-v the release tag
        id: de_v_tag
        run: |
          # Use the 'replace' function to remove the "v" from the tag
          TAG="${{ github.ref }}"
          TAG_WITHOUT_V="${TAG#refs/tags/v}"
          echo "Extracted tag: $TAG_WITHOUT_V"
          echo "tag_without_v=$TAG_WITHOUT_V" >> "$GITHUB_OUTPUT"
      - name: Show the modified tag
        run: |
          MODIFIED_TAG="${{ steps.de_v_tag.outputs.tag_without_v }}"
          echo "Modified tag: Release $MODIFIED_TAG"
      - name: Create Release
        id: create_release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ steps.de_v_tag.outputs.tag_without_v }}
          title: Release ${{ steps.de_v_tag.outputs.tag_without_v }}
